language: bash

servises:
- docker

script:
- docker-compose --file ./docker-compose.yml up -detach 
- docker ps -a
- docker-compose images

deploy:
 provider: script
 script: bash push.sh
 on:
  branch: main
