version: '3'

services:
    nginx:
        image: nginx
        restart: always
        ports:
            - 60:80   
            
            
    mariadb:
        image: mariadb
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes: 
            - ${DB_PATH}:/var/lib/mysql

    redmine:
        image: redmine
        restart: always
        ports:
            - 6080:3000
            
            
